Repository Goorm-Lucky7/ThinkTank_BE, pull requests merged in 2024-05, with the labels that each got.

#29 feat: 회원 정보 조회 기능 구현
  src/main/java/com/thinktank/api/controller/UserController.java
  src/main/java/com/thinktank/api/dto/user/response/UserResDto.java
  src/main/java/com/thinktank/api/service/UserService.java
  src/main/java/com/thinktank/api/service/auth/JwtProviderService.java
  src/main/java/com/thinktank/global/auth/AuthorizationThreadLocal.java
  src/main/java/com/thinktank/global/auth/annotation/Auth.java
  src/main/java/com/thinktank/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/thinktank/global/auth/handler/AuthUserArgumentResolver.java
  src/main/java/com/thinktank/global/config/SecurityConfig.java
  src/main/java/com/thinktank/global/config/WebConfig.java
Labels: 🚀 Be, 🎁 Feature

#32 feat: 좋아요 기능 구현
  src/main/java/com/thinktank/api/controller/LikeController.java
  src/main/java/com/thinktank/api/dto/like/request/LikeCreateDto.java
  src/main/java/com/thinktank/api/entity/Like.java
  src/main/java/com/thinktank/api/entity/UserLike.java
  src/main/java/com/thinktank/api/repository/LikeRepository.java
  src/main/java/com/thinktank/api/repository/UserLikeRepository.java
  src/main/java/com/thinktank/api/service/LikeService.java
  src/main/java/com/thinktank/global/error/model/ErrorCode.java
Labels: 🚀 Be, 🎁 Feature

#35 feat: 사용자 회원 탈퇴 기능 구현
  src/main/java/com/thinktank/api/controller/UserController.java
  src/main/java/com/thinktank/api/dto/user/request/UserReqDto.java
  src/main/java/com/thinktank/api/service/UserService.java
  src/main/java/com/thinktank/api/service/auth/AuthenticationService.java
Labels: 🚀 Be, 🎁 Feature

#39 refactor: 엔티티 수정
  src/main/java/com/thinktank/api/entity/ProfileImage.java
  src/main/java/com/thinktank/global/common/util/GlobalConstant.java
  src/main/java/com/thinktank/global/error/model/ErrorCode.java
Labels: 🚀 Be, 🔧 Refactor

#41 feat: 마이페이지 사용자 정보 수정 기능 구현
  src/main/java/com/thinktank/api/controller/UserController.java
  src/main/java/com/thinktank/api/controller/UserProfileController.java
  src/main/java/com/thinktank/api/dto/profileImage/request/ProfileImageReqDto.java
  src/main/java/com/thinktank/api/dto/user/request/UserDeleteDto.java
  src/main/java/com/thinktank/api/dto/user/request/UserUpdateDto.java
  src/main/java/com/thinktank/api/entity/ProfileImage.java
  src/main/java/com/thinktank/api/entity/User.java
  src/main/java/com/thinktank/api/repository/ProfileImageRepository.java
  src/main/java/com/thinktank/api/service/UserProfileService.java
  src/main/java/com/thinktank/api/service/UserService.java
  src/main/java/com/thinktank/global/config/SecurityConfig.java
  src/main/java/com/thinktank/global/config/WebConfig.java
Labels: 🚀 Be, 🎁 Feature

#53 refactor: 자바 채점시스템 로직 변경
  src/main/java/com/thinktank/api/controller/JudgeController.java
  src/main/java/com/thinktank/api/dto/judge/request/JudgeDto.java
  src/main/java/com/thinktank/api/entity/UserCode.java
  src/main/java/com/thinktank/api/repository/UserCodeRepository.java
  src/main/java/com/thinktank/api/service/JudgeService.java
  src/main/java/com/thinktank/global/common/util/JavaJudge.java
  src/main/java/com/thinktank/global/common/util/Template.java
  src/main/resources/application-local.yml
Labels: 🚀 Be, 🔧 Refactor

#44 feat: Post 전체 조회 기능 구현
  src/main/java/com/thinktank/api/controller/PostController.java
  src/main/java/com/thinktank/api/dto/page/response/PageInfoDto.java
  src/main/java/com/thinktank/api/dto/post/response/PagePostResponseDto.java
  src/main/java/com/thinktank/api/dto/post/response/PostsResponseDto.java
  src/main/java/com/thinktank/api/dto/user/response/SimpleUserResDto.java
  src/main/java/com/thinktank/api/entity/Post.java
  src/main/java/com/thinktank/api/repository/CommentRepository.java
  src/main/java/com/thinktank/api/repository/LikeRepository.java
  src/main/java/com/thinktank/api/repository/UserLikeRepository.java
  src/main/java/com/thinktank/api/service/PostService.java
  src/main/java/com/thinktank/api/service/UserLikeService.java
  src/main/java/com/thinktank/global/common/util/GlobalConstant.java
Labels: 🚀 Be, 🎁 Feature

#55 refactor: 자바스크립트 채점 로직 수정
  src/main/java/com/thinktank/global/common/util/JavaJudge.java
  src/main/java/com/thinktank/global/common/util/JavaScriptJudge.java
  src/main/java/com/thinktank/global/common/util/Template.java
Labels: 🚀 Be, 🔧 Refactor

#46 feat: 마이페이지 사용자 정보 조회 기능 구현
  src/main/java/com/thinktank/api/controller/UserController.java
  src/main/java/com/thinktank/api/controller/UserProfileController.java
  src/main/java/com/thinktank/api/dto/profileImage/response/ProfileImageResDto.java
  src/main/java/com/thinktank/api/dto/user/response/UserResDto.java
  src/main/java/com/thinktank/api/entity/ProfileImage.java
  src/main/java/com/thinktank/api/service/UserProfileService.java
  src/main/java/com/thinktank/api/service/UserService.java
  src/main/java/com/thinktank/global/common/util/GlobalConstant.java
  src/main/java/com/thinktank/global/error/model/ErrorCode.java
Labels: 🚀 Be, 🎁 Feature

#50 feat: 게시글과 좋아요에 유저 추가, 게시글 생성 시 테스트케이스 추가
  src/main/java/com/thinktank/api/controller/LikeController.java
  src/main/java/com/thinktank/api/controller/PostController.java
  src/main/java/com/thinktank/api/dto/post/request/PostCreateDto.java
  src/main/java/com/thinktank/api/entity/Post.java
  src/main/java/com/thinktank/api/entity/TestCase.java
  src/main/java/com/thinktank/api/service/LikeService.java
  src/main/java/com/thinktank/api/service/PostService.java
Labels: 🚀 Be, 🎁 Feature

#59 feat: 사용자 무한반복문 코드 방지하기
  src/main/java/com/thinktank/api/controller/JudgeController.java
  src/main/java/com/thinktank/global/common/util/GlobalConstant.java
  src/main/java/com/thinktank/global/common/util/JavaJudge.java
  src/main/java/com/thinktank/global/common/util/Template.java
Labels: 🚀 Be, 🎁 Feature

#57 feat: 게시글 단건 조회 기능 추가
  src/main/java/com/thinktank/api/controller/PostController.java
  src/main/java/com/thinktank/api/dto/post/response/PostDetailResponseDto.java
  src/main/java/com/thinktank/api/repository/TestCaseRepository.java
  src/main/java/com/thinktank/api/service/PostService.java
Labels: 🚀 Be, 🎁 Feature

#49 feat: 사용자 댓글 식별 기능 구현
  src/main/java/com/thinktank/api/controller/CommentController.java
  src/main/java/com/thinktank/api/dto/comment/page/response/PageInfoDto.java
  src/main/java/com/thinktank/api/dto/comment/response/CommentResponseDto.java
  src/main/java/com/thinktank/api/dto/comment/response/CommentsResponseDto.java
  src/main/java/com/thinktank/api/service/CommentService.java
Labels: 🚀 Be, 🎁 Feature

#56 feat: refreshToken 관리를 위한 Redis 도입 및 CORS 설정
  build.gradle
  src/main/java/com/thinktank/api/controller/UserController.java
  src/main/java/com/thinktank/api/dto/auth/TokenSaveValue.java
  src/main/java/com/thinktank/api/entity/ProfileImage.java
  src/main/java/com/thinktank/api/entity/User.java
  src/main/java/com/thinktank/api/repository/redis/HashRedisRepository.java
  src/main/java/com/thinktank/api/repository/redis/TokenRepository.java
  src/main/java/com/thinktank/api/service/auth/AuthenticationService.java
  src/main/java/com/thinktank/api/service/auth/JwtProviderService.java
  src/main/java/com/thinktank/global/config/RedisConfig.java
  src/main/java/com/thinktank/global/config/SecurityConfig.java
  src/main/java/com/thinktank/global/config/WebConfig.java
  src/main/resources/application-local.yml
  src/test/java/com/thinktank/api/service/auth/JwtProviderServiceTest.java
  src/test/java/com/thinktank/support/fixture/JwtFixture.java
Labels: 🚀 Be, 🎁 Feature

#62 feat: 게시글 삭제 구현
  src/main/java/com/thinktank/api/controller/PostController.java
  src/main/java/com/thinktank/api/dto/post/request/PostDeleteDto.java
  src/main/java/com/thinktank/api/repository/LikeRepository.java
  src/main/java/com/thinktank/api/repository/TestCaseRepository.java
  src/main/java/com/thinktank/api/repository/UserLikeRepository.java
  src/main/java/com/thinktank/api/service/PostService.java
Labels: 🚀 Be, 🎁 Feature

#65 chore: 배포파일 추가
  .gitignore
  Dockerfile
  build.gradle
  k8s/deployment.yaml
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/mysqldb.yaml
  k8s/service.yaml
Labels: 🚀 Be

#70 feat: 타인 열람 시 사용자 정보 조회
  src/main/java/com/thinktank/api/controller/UserPostController.java
  src/main/java/com/thinktank/api/dto/post/response/PagePostProfileResponseDto.java
  src/main/java/com/thinktank/api/dto/post/response/PagePostResponseDto.java
  src/main/java/com/thinktank/api/dto/post/response/PostProfileResponseDto.java
  src/main/java/com/thinktank/api/dto/post/response/PostResponseDto.java
  src/main/java/com/thinktank/api/dto/post/response/PostSolvedResponseDto.java
  src/main/java/com/thinktank/api/dto/problemType/request/ProblemTypeDto.java
  src/main/java/com/thinktank/api/dto/user/response/UserProfileResDto.java
  src/main/java/com/thinktank/api/entity/ProblemType.java
  src/main/java/com/thinktank/api/repository/CommentRepository.java
  src/main/java/com/thinktank/api/repository/PostRepository.java
  src/main/java/com/thinktank/api/repository/UserCodeRepository.java
  src/main/java/com/thinktank/api/repository/UserLikeRepository.java
  src/main/java/com/thinktank/api/service/PostService.java
  src/main/java/com/thinktank/api/service/UserPostService.java
Labels: 🚀 Be, 🎁 Feature

#77 chore: 배포 설정
  Dockerfile
  docker-compose.yml
  src/main/resources/application.yml
Labels: 🚀 Be

#79 chore: 도커 파일 수정
  Dockerfile
Labels: 🚀 Be

#81 refactor: 도커파일 수정
  Dockerfile
Labels: 🚀 Be

#85 feat: 로그인 없이 댓글 목록 조회하기
  src/main/java/com/thinktank/api/service/CommentService.java
  src/main/java/com/thinktank/global/config/SecurityConfig.java
Labels: 🚀 Be, 🎁 Feature

#88 fix: 인증 문제 해결
  docker-compose.yml
Labels: 🚀 Be

#92 refactor: 게시글 생성시 채점
  src/main/java/com/thinktank/api/service/PostService.java
  src/main/java/com/thinktank/global/common/util/JavaJudge.java
  src/main/java/com/thinktank/global/common/util/JavaScriptJudge.java
  src/main/java/com/thinktank/global/common/util/Template.java
  src/main/resources/application.yml
Labels: 🚀 Be, 🔧 Refactor

#80 feat: 마이페이지 사용자 프로필 이미지 삭제 기능 구현
  src/main/java/com/thinktank/api/controller/UserController.java
  src/main/java/com/thinktank/api/controller/UserProfileController.java
  src/main/java/com/thinktank/api/dto/TokenReqDto.java
  src/main/java/com/thinktank/api/dto/TokenResDto.java
  src/main/java/com/thinktank/api/dto/user/request/UserUpdateDto.java
  src/main/java/com/thinktank/api/entity/ProfileImage.java
  src/main/java/com/thinktank/api/entity/User.java
  src/main/java/com/thinktank/api/service/UserProfileService.java
  src/main/java/com/thinktank/api/service/UserService.java
  src/main/java/com/thinktank/api/service/auth/AuthenticationService.java
  src/main/java/com/thinktank/api/service/auth/JwtProviderService.java
  src/main/java/com/thinktank/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/thinktank/global/error/model/ErrorCode.java
  src/main/resources/application-local.yml
Labels: 🚀 Be, 🎁 Feature

#93 refactor: 게시글 관련 모든 조회 시 비로그인 사용자도 가능하도록 수정
  src/main/java/com/thinktank/api/controller/PostController.java
  src/main/java/com/thinktank/api/controller/UserPostController.java
  src/main/java/com/thinktank/api/dto/post/request/PostDeleteDto.java
  src/main/java/com/thinktank/api/dto/problemType/request/ProblemTypeDto.java
  src/main/java/com/thinktank/api/repository/UserRepository.java
  src/main/java/com/thinktank/api/service/PostService.java
  src/main/java/com/thinktank/api/service/UserPostService.java
  src/main/java/com/thinktank/global/config/SecurityConfig.java
  src/main/java/com/thinktank/global/error/model/ErrorCode.java
  src/main/resources/application.yml
Labels: 🚀 Be, 🔧 Refactor

#96 refactor: 자바스크립트 채점시 무한반복문 방지 구현
  src/main/java/com/thinktank/api/controller/JudgeController.java
  src/main/java/com/thinktank/global/common/util/JavaJudge.java
  src/main/java/com/thinktank/global/common/util/JavaScriptJudge.java
  src/main/java/com/thinktank/global/common/util/Template.java
  src/main/java/com/thinktank/global/config/SecurityConfig.java
  src/main/java/com/thinktank/global/error/model/ErrorCode.java
  src/main/resources/application.yml
Labels: 🚀 Be, 🔧 Refactor

#100 PageInfoDto -> PageDto 수정, CommentService 수정
  src/main/java/com/thinktank/api/dto/comment/response/CommentsResponseDto.java
  src/main/java/com/thinktank/api/dto/page/response/PageInfo.java
  src/main/java/com/thinktank/api/dto/post/response/PagePostProfileResponseDto.java
  src/main/java/com/thinktank/api/dto/post/response/PagePostResponseDto.java
  src/main/java/com/thinktank/api/service/CommentService.java
  src/main/java/com/thinktank/api/service/PostService.java
  src/main/java/com/thinktank/api/service/UserPostService.java
Labels: 🚀 Be, 🔧 Refactor

#102 refactor: 마이페이지 사용자 정보 수정 로직 리팩토링
  src/main/java/com/thinktank/api/controller/UserController.java
  src/main/java/com/thinktank/api/controller/UserProfileController.java
  src/main/java/com/thinktank/api/dto/auth/TokenReqDto.java
  src/main/java/com/thinktank/api/dto/auth/TokenResDto.java
  src/main/java/com/thinktank/api/dto/profileImage/request/ProfileImageReqDto.java
  src/main/java/com/thinktank/api/dto/profileImage/response/ProfileImageResDto.java
  src/main/java/com/thinktank/api/dto/user/request/UserDeleteDto.java
  src/main/java/com/thinktank/api/dto/user/request/UserUpdateDto.java
  src/main/java/com/thinktank/api/dto/user/response/UserProfileResDto.java
  src/main/java/com/thinktank/api/dto/user/response/UserResDto.java
  src/main/java/com/thinktank/api/entity/ProfileImage.java
  src/main/java/com/thinktank/api/service/UserPostService.java
  src/main/java/com/thinktank/api/service/UserProfileService.java
  src/main/java/com/thinktank/api/service/UserService.java
  src/main/java/com/thinktank/api/service/auth/AuthenticationService.java
  src/main/java/com/thinktank/global/common/util/GlobalConstant.java
Labels: 🚀 Be, 🔧 Refactor

#111 feat: 미인증 사용자 접근 허용 기능 구현
  src/main/java/com/thinktank/global/auth/annotation/Auth.java
  src/main/java/com/thinktank/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/thinktank/global/auth/handler/AuthUserArgumentResolver.java
Labels: 🚀 Be, 🎁 Feature

#114 refactor: ErrorCode 리팩토링
  src/main/java/com/thinktank/api/service/CommentService.java
  src/main/java/com/thinktank/api/service/JudgeService.java
  src/main/java/com/thinktank/api/service/LikeService.java
  src/main/java/com/thinktank/api/service/PostService.java
  src/main/java/com/thinktank/api/service/UserPostService.java
  src/main/java/com/thinktank/api/service/UserService.java
  src/main/java/com/thinktank/api/service/auth/AuthenticationService.java
  src/main/java/com/thinktank/api/service/auth/JwtProviderService.java
  src/main/java/com/thinktank/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/thinktank/global/auth/handler/AuthUserArgumentResolver.java
  src/main/java/com/thinktank/global/common/util/JavaJudge.java
  src/main/java/com/thinktank/global/common/util/JavaScriptJudge.java
  src/main/java/com/thinktank/global/error/model/ErrorCode.java
Labels: 🚀 Be, 🔧 Refactor

#116 refactor: 로그인 한 사용자 정보 저장하도록 수정
  src/main/java/com/thinktank/api/controller/PostController.java
  src/main/java/com/thinktank/api/controller/UserPostController.java
  src/main/java/com/thinktank/api/dto/post/request/PostCreateDto.java
  src/main/java/com/thinktank/api/entity/Post.java
  src/main/java/com/thinktank/api/repository/ProfileImageRepository.java
  src/main/java/com/thinktank/api/repository/UserLikeRepository.java
  src/main/java/com/thinktank/api/repository/UserRepository.java
  src/main/java/com/thinktank/api/service/PostService.java
  src/main/java/com/thinktank/api/service/UserLikeService.java
  src/main/java/com/thinktank/api/service/UserPostService.java
  src/main/java/com/thinktank/api/service/auth/JwtProviderService.java
  src/main/java/com/thinktank/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/thinktank/global/auth/handler/AuthUserArgumentResolver.java
  src/main/java/com/thinktank/global/config/SecurityConfig.java
Labels: 🚀 Be, 🔧 Refactor

#119 refactor: 변수명 통일, 타인 프로필 조회 시 페이징 처리 수정, 전반적인 코드 스타일 수정, 카테고리 추가
  src/main/java/com/thinktank/api/dto/post/response/PostDetailResponseDto.java
  src/main/java/com/thinktank/api/dto/post/response/PostProfileResponseDto.java
  src/main/java/com/thinktank/api/dto/post/response/PostSolvedResponseDto.java
  src/main/java/com/thinktank/api/dto/post/response/PostsResponseDto.java
  src/main/java/com/thinktank/api/dto/user/response/SimpleUserResDto.java
  src/main/java/com/thinktank/api/entity/Category.java
  src/main/java/com/thinktank/api/entity/Language.java
  src/main/java/com/thinktank/api/entity/Post.java
  src/main/java/com/thinktank/api/repository/PostRepository.java
  src/main/java/com/thinktank/api/repository/UserCodeRepository.java
  src/main/java/com/thinktank/api/repository/UserLikeRepository.java
  src/main/java/com/thinktank/api/repository/UserRepository.java
  src/main/java/com/thinktank/api/service/PostService.java
  src/main/java/com/thinktank/api/service/UserPostService.java
Labels: 🚀 Be, 🔧 Refactor, ✨ Fix

#134 feat: 소셜 로그인 구현
  build.gradle
  src/main/java/com/thinktank/api/dto/auth/OAuthProviderUpdateDto.java
  src/main/java/com/thinktank/api/entity/User.java
  src/main/java/com/thinktank/api/entity/auth/CustomOAuth2User.java
  src/main/java/com/thinktank/api/entity/auth/OAuthProvider.java
  src/main/java/com/thinktank/api/repository/UserRepository.java
  src/main/java/com/thinktank/api/service/UserService.java
  src/main/java/com/thinktank/api/service/auth/CustomOAuth2UserService.java
  src/main/java/com/thinktank/api/service/auth/JwtProviderService.java
  src/main/java/com/thinktank/api/service/auth/OAuthLoginService.java
  src/main/java/com/thinktank/global/auth/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/thinktank/global/auth/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/thinktank/global/config/OAuthProperties.java
  src/main/java/com/thinktank/global/config/PasswordEncoderConfig.java
  src/main/java/com/thinktank/global/config/SecurityConfig.java
  src/main/java/com/thinktank/global/error/model/ErrorCode.java
  src/main/resources/application-local.yml
Labels: 🚀 Be, 🎁 Feature

#137 refactor: post, like 부분 전반적으로 코드 스타일 수정
  src/main/java/com/thinktank/api/dto/like/request/LikeCreateDto.java
  src/main/java/com/thinktank/api/service/LikeService.java
  src/main/java/com/thinktank/api/service/PostService.java
  src/main/java/com/thinktank/api/service/UserPostService.java
Labels: 🚀 Be, 🔧 Refactor

#139 refactor : 엔티티 코드 크기 수정
  src/main/java/com/thinktank/api/dto/judge/request/JudgeDto.java
  src/main/java/com/thinktank/api/dto/post/request/PostCreateDto.java
  src/main/java/com/thinktank/api/entity/Post.java
  src/main/java/com/thinktank/api/entity/UserCode.java
Labels: 🚀 Be, 🔧 Refactor

#140 refactor: 게시글 로직 리팩토링
  src/main/java/com/thinktank/api/repository/CommentRepository.java
  src/main/java/com/thinktank/api/repository/LikeRepository.java
  src/main/java/com/thinktank/api/repository/PostRepository.java
  src/main/java/com/thinktank/api/repository/TestCaseRepository.java
  src/main/java/com/thinktank/api/repository/UserCodeRepository.java
  src/main/java/com/thinktank/api/repository/UserLikeRepository.java
  src/main/java/com/thinktank/api/service/PostService.java
Labels: 🚀 Be, 🔧 Refactor

#141 refactor: 사용자 프로필 수정 로직 변경
  src/main/java/com/thinktank/api/entity/User.java
  src/main/java/com/thinktank/api/entity/UserCode.java
  src/main/java/com/thinktank/api/service/UserService.java
Labels: 🚀 Be, 🔧 Refactor

#145 Fix/#144 fix kakao login
  src/main/java/com/thinktank/ThinktankApplication.java
  src/main/java/com/thinktank/global/config/OAuthProperties.java
  src/main/java/com/thinktank/global/config/SecurityConfig.java
Labels: 🚀 Be, ✨ Fix

#148 add: favicon.ico 수정
  src/main/resources/static/favicon.ico
Labels: 🚀 Be, ✨ Fix

#150 remove: test 삭제
  src/test/java/com/thinktank/ThinktankApplicationTests.java
Labels: 🚀 Be, ✨ Fix
